name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and analyze
        env:
          GITHUB_TOKEN: 0ec24bf8-94cd-4e79-b1f1-00b50cb4c56c
          SONAR_TOKEN: 811c9a490983734401ba4e491eaefc8bfa7281de
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=worlflows-java2
          -Dsonar.login=811c9a490983734401ba4e491eaefc8bfa7281de